from lps36.errors.error import LPS36Error
from lps36.errors.connection import ConnectionError
